name: extractor_server
description: High-performance audio stream extractor service for CloudBeatz using youtube_explode_dart
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  youtube_explode_dart:
    git:
      url: https://github.com/AkashKumar-Behera/youtube_explode_dart.git
      ref: master
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  http: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
